version: "3"
services:
  zerotier:
    container_name: zerotier
    build: ./build/zerotier/
    restart: unless-stopped
    volumes:
      - ./build/zerotier/connect2anycast.sh:/connect2anycast.sh
      - ./build/zerotier/start.sh:/start.sh
      - ./data/zerotier:/var/lib/zerotier-one
      - ./data/zerotier-dump.txt:/root/zerotier_dump.txt
    environment:
      - username=${username}
      - apikey=${passowrd}
      - region=${region}
      - as=${as}
      - ip41=${ip41}
      - ip61=${ip61}
      - ip42=${ip42}
      - ip62=${ip62}
      - gw4=${gw4}
      - gw6=${gw6}
    network_mode: host
    privileged: true
  bird:
    container_name: bird
    build: ./build/bird/
    restart: unless-stopped
    volumes:
      - ./build/bird/start.sh:/start.sh
      - ./config/bird-template.conf:/etc/bird/bird-template.conf
      - ./config/bird6-template.conf:/etc/bird/bird6-template.conf
      - ./data/zerotier-dump.txt:/root/zerotier_dump.txt
    environment:
      - region=${region}
      - as=${as}
      - ip41=${ip41}
      - ip61=${ip61}
      - ip42=${ip42}
      - ip62=${ip62}
      - gw4=${gw4}
      - gw6=${gw6}
      - bgppassword=${bgppassword}
    network_mode: host
    privileged: true